### ISSUE TITLE
Which index plugin works best for sidebar?

### ISSUE THREAD

**Issue by shivahnshankar** [my17560/dokuwiki-template-readthedokus#21]
Hi
My understanding is that with the new hierarchical sidebar, I should be able to use an index plugin (like navi, simplenavi etc) to generate the sidebar automatically with all the pages in a given namespace. This is not working properly for me, atleast with the  simplenavi plugin.. 
Any recommendation on how the sidebar can be generated automatically for one or more namespaces?
Thanks

**Comment by my17560** [comment]
Hi, I updated the theme on GitHub to support simplenavi plugin. Since I haven't updated it officially yet, re-install the theme. Could you try this? If it is OK, then I'll release it.

Please be noted that this is highly dependent on HTML which the plugin outputs, other than simplenavi plugin won't work. If you need other plugins to support, let me know.

**Comment by shivahnshankar** [comment]
Great thanks. Works well as far as i can tell. However, with the useheadings option, there is a obvious jitter when i click on various links in the sidebar. Not sure whether this is related to the template or not.

**Comment by my17560** [comment]
Thanks for your report. I couldn't re-produce the jittering on my environment. The theme uses javascript to jump to anchor so it might be conflicting with something.

I have some questions:
1. Which os and browser are you using?
2. Are you using any plugins?
3. Does this happen when you switched to another theme?
4. Does this happen on the same page link or another page link or both?

**Comment by my17560** [comment]
Hi, I'm closing this issue for now. Please re-open or throw a new issue anytime if you want!
