### ISSUE TITLE
No login, sitemap etc buttons when logged out

### ISSUE THREAD

**Issue by Juuxel** [my17560/dokuwiki-template-readthedokus#23]
The whole "toolbox" in the page footer is disabled when you're logged out, which means logged out users can't view sitemap, recent changes - or most importantly, *log in*. I think it's this check that disables it entirely:

https://github.com/my17560/dokuwiki-template-readthedokus/blob/e06d2f1cd89ccd39f600b515f21e557af02d29a6/tpl_parts/tpl_pagefooter.html#L17

**Comment by my17560** [comment]
Hi!

Yes, I do so intentionally. Because I wanted it to look like a normal website, not like a wiki site when logged out.
So you need to go to each page directly when you are logged out, e.g. append "&do=login" to the current URL to go to the login page.

Maybe I can add an option to show the toolbox even when you are logged out if you want, like "Show the toolbox when logged out".

**Comment by my17560** [comment]
Since it was an easy fix and it might be useful to other people I added the option and released it.

Update the theme and check "Show toolbox even when logged out" in the configuration option to show the toolbox always.

**Comment by Juuxel** [comment]
Just tried it out, it works great! Thanks for the quick fix 😄
