### ISSUE TITLE
Stylesheets dokuwiki/css/_search.css and dokuwiki/css/_admin.css missing when using "readthedokus" template

### ISSUE THREAD

**Issue by fthommen** [my17560/dokuwiki-template-readthedokus#5]
Hi, when using the "readthedokus" template with DokuWiki 2020-07-29 "Hogfather", I get the following two error message on top of each page:

```
Stylesheet ../dokuwiki/css/_search.css not found, using ../dokuwiki/css/_search.less instead. Please contact developer of "readthedokus" template.
```
```
Stylesheet ../dokuwiki/css/_admin.css not found, using ../dokuwiki/css/_admin.less instead. Please contact developer of "readthedokus" template.
```
See also this screenshot:
![readthedokus_errormessages](https://user-images.githubusercontent.com/279232/132706665-33583713-b405-4602-9616-cbaad53d9c7d.png)

**Comment by my17560** [comment]
Hi! There were some mistakes in style.ini attached to this theme and I fixed them. Reinstalling the theme should fix it.

It seems like enabling "allowdebug" option makes these warning messages visible. Since I've never enabled this option before, I didn't know about these warnings. Thanks for your report.

**Comment by fthommen** [comment]
I had totally forgotten, that we had debugging enabled.  Thanks for the reminder :-)  Yes, updating the template fixed the issue.  Thanks for your quick reaction
